package com.testyris.testyris;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.testyris.testyris.model.LocationEntity;
import com.testyris.testyris.repository.LocationRepository;

import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;

import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.io.ParseException;
import org.locationtech.jts.io.WKTReader;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.wololo.geojson.Feature;
import org.wololo.geojson.GeoJSON;
import org.wololo.jts2geojson.GeoJSONReader;
import org.wololo.jts2geojson.GeoJSONWriter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/*
@RunWith(SpringRunner.class)
@SpringBootTest
class TestYrisApplicationTests {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private LocationRepository locationRepository;

	@Test
	void contextLoads() {
	}

	/*
	@Test
	public void shouldConvertWktToGeometry() throws ParseException {
		Geometry geometry = wktToGeometry("POINT (2 5)");
		assertEquals("Point", geometry.getGeometryType());
		assertTrue(geometry instanceof Point);
	}*/

/*
	@Test
	public void loadSelectPoints() throws ParseException {
		List<LocationEntity> produits = locationRepository.findAll();

		System.out.println(produits);

		GeoJSONWriter writer = new GeoJSONWriter();
		GeoJSON json = writer.write(produits.get(0).getGeometry());
		String jsonstring = json.toString();

		System.out.println(jsonstring);
	}


	@Test
	public void shouldInsertGeometryPoint() throws ParseException {

		LocationEntity entity = new LocationEntity();
		entity.setName("yala");
		//Geometry geometry = new WKTReader().read("POINT (2 5)");
		Geometry geometry = new GeometryFactory().createPoint(new Coordinate(12.34343, 12.232424));
		entity.setGeometry(geometry);
		//entity.setGeometry((Point) wktToGeometry("POINT (1 1)"));
		System.out.println(entity);
		LocationEntity coucou = locationRepository.save(entity);
		//session.persist(entity);
		System.out.println(coucou.getId());

		//assertEquals("POINT (1 1)", fromDb.getPoint().toString());
		//assertTrue(geometry instanceof Point);
	}
}
*/